### ISSUE TITLE
Play only 1 track and shutdown app spotify

### ISSUE THREAD

**Issue by popeyaho** [meik1710/Spotify1710#1]
As the title, can you help?

**Comment by meik1710** [comment]
Yes, there are a few bugs that can cause a crash. Im not quite sure why, but i think its related to my hooking method. 
Just restart Spotify with Spotify1710 and make sure you are on the latest version

**Comment by popeyaho** [comment]
thank you for the answer, this ver 1.1.5.153.gf614956d
ran on win10 x64
open with Spotify1710 and same issue

**Comment by meik1710** [comment]
Im trying to fix it
