### ISSUE TITLE
IDP.ALEXA.51 detect by Avast, false positive?

### ISSUE THREAD

**Issue by z3nth10n** [meik1710/Spotify1710#2]

**Comment by meik1710** [comment]
yes, should be a false positive. You can look into the source code anyway

**Comment by z3nth10n** [comment]
I know it, I'm doing a reimplementation of you code but in C#: https://github.com/uta-org/SpotifySharper

I would like to use [AViator](https://github.com/Ch0pin/AVIator) to solve this issue, because almost all antivirus detect injection as a posible cause of virus.
