### ISSUE TITLE
Incongruous method name: Patch --> PatchAds

### ISSUE THREAD

**Issue by z3nth10n** [meik1710/Spotify1710#4]
Well, inside [HookingBase.cpp](https://github.com/meik1710/Spotify1710/blob/b122b2c4ad2625d89d09fcea7e8ba333f6ebe09c/HookingBase/HookingBase.cpp), on the `DLLFunction` entry method, you are calling PatchSpotify that calls Patch method.

It's supposed to be defined in `SpotifyPatchAds.h`, but there is only one method called that is simila: `PatchAds`, what's happening with the source code of this project?

**Comment by meik1710** [comment]
Yes you are right, i have messed up the last update. I will update it today
